#!/usr/bin/env bash
# This Bash script transfers a file from a client to a server using scp.

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

if scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "${username}@${server_ip}:~/"; then
  echo "File successfully transferred to ${username}@${server_ip}:~/"
else
  echo "File transfer failed"
fi
