#!/usr/bin/env bash
# Bash script to install Nginx web server and configure it

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
