#!/usr/bin/env bash

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple index.html for the default server block
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the Nginx configuration for redirection
config_block="
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.kharisrem.tech\$request_uri;
    }

    # Add any other server configuration as needed
}
"

# Add the new server block to the default Nginx configuration
echo "$config_block" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test the Nginx configuration for syntax errors
if sudo nginx -t; then
    sudo service nginx reload
fi
