#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that returns an HTTP 404 error code and contains the string "Ceci n'est pas une page."

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page with the required content
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Create an Nginx configuration file for the custom 404 page
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html;

    server_name _;

    error_page 404 /custom_404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test the Nginx configuration for syntax errors
if sudo nginx -t; then
    sudo systemctl reload nginx
fi
