#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# SSH connection using single-character flags
ssh -i ~/.ssh/school ubuntu@34.207.62.121
